changes to build command

diff --git a/runBuild b/runBuild
--- a/runBuild
+++ b/runBuild
@@ -25,4 +25,14 @@ then
 fi
 
 (cd ./cli/ && ./runBuild)
+if [[ $? -ne 0 ]]
+then
+    echo "Failed to build"
+	exit 1
+fi
 (cd ./downloader/ && ./runBuild)
+if [[ $? -ne 0 ]]
+then
+    echo "Failed to build"
+	exit 1
+fi
