Ee feature flag (#533)
* adds empty ee module

* changes to runBuild to add ee jar

* adds ee built jar

* adds test function to ee module

* removes test function

* adds skeleton logic for feature flag

* fixes a bug related to no syncing on init

* makes logic simpler

* renames

* improves code flow

* adds a TODO

* adds logic for querying API and also for formatting code for sub modules of the core

* adds comments about all scenarios of api and db liveness

* adds TODOs for long term future changes

* changes ee to be dynamically loaded instead of statically

* adds ee jar initially

* adds ee stuff to downloader

* updates contributing guide

* gets ee package to dynamically load in the core

* modifies a comment

* adds a small TODO comment in test

* changes logging message

* changes copyright and adds storage layer to EE

* clarifies some TODOs

* adds core version and telemetry ID to license key sync API

* adds telemetry ID on core startup

* adds code for license check cronjob

* fails core start if licese check in db fails

* refactors and removes some old TODOs

* adds API to load license key

* renames file

* refactors and adds skeleton for airgapped license check

* adds more APIs for ee stuff

* adds new API to get enabled features

* adds logger

* adds logging

* refactors code

* adds a TODO comment

* fixes small bug

* adds s TODO

* adds more API and skeleton for paid feature

* adds db queries

* adds JWT verification code

* removes unnecessary code

* small fix

* fixes a bug

* changes license check path

* small change

* adds public key info for stateless lilcense key

* changes public key

* adds a TODO and adds test feature

* removes TODO

* Ee feature flag tests (#545)

* inital commit

* adds some basic tests

* adds more test

* small changes

* small changes

* small changes

* reverses dependency

* moves ee test to ee folder

* adds test files to ee folder

Co-authored-by: rishabhpoddar <rishabh.poddar@gmail.com>

* removes wrong copyright from ee folder files

* adds a few tests

* adds more tests

* adds more tests

* adds JWT parsing test

* adds more tests

* removes unnecessary comment

* adds more tests

* more tests

* small bug fix

* adds more tests

* adds test keys

* adds more test keys

* modifies one test

* removes unnecesary logging and refactors function name

* adds more tests

* more tests

* adds more tests

* adds more tests

* more tests

* fixes a bug

* adds more tests

* fixes test for in mem

* fixes bug in test

* test: Adds API tests for EE feature flag (#547)

* starts adding tests

* adds more tests

* adds more SetLicenseKeyAPITests

* adds more tests

* fixes

* fixes

* implements feedback

* fixes

* updates licenses, cdi version and changelog

Co-authored-by: Joel Coutinho <joelsteve97@hotmail.com>

diff --git a/runBuild b/runBuild
--- a/runBuild
+++ b/runBuild
@@ -36,3 +36,9 @@ then
     echo "Failed to build"
 	exit 1
 fi
+(cd ./ee/ && ./runBuild "$@")
+if [[ $? -ne 0 ]]
+then
+    echo "Failed to build"
+	exit 1
+fi
