fix: release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,14 +1,28 @@
 name: Release
 on:
-  workflow_dispatch:
-    inputs:
-      branch:
-        description: 'Branch to release'
-        type: string
-        required: true
+  workflow_run:
+    workflows:
+    #   - "Unit Tests"
+      - "Publish Dev Docker Image"
+    types:
+      - completed
+    branches:
+      - "**" # TODO: change to x.y
 
 jobs:
   on-success:
+    if: |
+      github.event.workflow_run.conclusion == 'success' &&
+      github.event.workflow_run.head_repository.full_name == github.repository
     runs-on: ubuntu-latest
     steps:
-      - run: echo 'The Run Tests workflow passed'
+      - name: Check if workflow is being re-run
+        id: check_rerun
+        run: |
+          if [[ "${{ github.run_attempt }}" == "1" ]]; then
+            echo "First attempt - failing intentionally"
+            exit 1
+          else
+            echo "Re-run attempt - passing"
+            echo "The Run Tests workflow passed"
+          fi
