fix: unit test gha

diff --git a/.github/workflows/unit-test.yml b/.github/workflows/unit-test.yml
--- a/.github/workflows/unit-test.yml
+++ b/.github/workflows/unit-test.yml
@@ -37,3 +37,10 @@ jobs:
         run: cd ../supertokens-root && ./utils/setupTestEnv --local
       - name: Run tests
         run: cd ../supertokens-root && ./gradlew test
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/test/TEST-*.xml'
+          detailed_summary: true
+          include_passed: true
